name: Pull Request
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  context:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT" | jq .

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT" | jq .

      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT" | jq .

      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT" | jq .

      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT" | jq .

      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT" | jq .

  base:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Dump misc
        run: |
          set -x
          pwd
          whoami
          uname -a

      - name: Dump env
        run: printenv | sort

      - name: Dump set
        run: set | sort
